### ISSUE TITLE
Example of how to use with bs-form-group

### ISSUE THREAD

**Issue by danjac** [offirgolan/ember-bootstrap-cp-validations#6]
```
    {{#bs-form-group validation='???'}}
        <label class = "control-label">Title</label>
        {{bs-input type="text" value=model.title}}
    {{/bs-form-group}}

```

What should the value of validation be here?

**Comment by offirgolan** [comment]
Unfortunately `bs-form-group` isnt supported. Is there a reason you cant just use `bs-form-element`?

**Comment by danjac** [comment]
bs-form-element is fine, thanks.

**Comment by offirgolan** [comment]
@danjac 👍 . If you get into a use-case where bs-form-group is needed, please feel free to reopen.
